### PR TITLE
habit page

### PR DESCRIPTION
**Pull request by atn34**

### CODE REVIEW

**Comment by atn34** [comment]
@whittlbc This is ready for review

**Comment by whittlbc** [comment]
kk will look at challenge page first

**Comment by whittlbc** [comment]
Gonna make some changes and commit directly to this one.

**Comment by atn34** [comment]
ping @whittlbc

**Comment by whittlbc** [comment]
@atn34 ignoring this pr until after everything else with the demo is done/ready.

**Pull request closed without merging**
